# Generated by Django 4.1.2 on 2022-11-10 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='external_id',
            field=models.CharField(default=0, editable=False, max_length=80, verbose_name='Внешний ИД'),
        ),
    ]
