# Generated by Django 4.1.2 on 2022-11-27 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_shop_user_alter_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
